repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: ./scripts/lint.sh
        language: system
        types: [python]
        pass_filenames: false
      - id: format
        name: format
        entry: ./scripts/format.sh
        language: system
        types: [python]
        pass_filenames: false
      - id: test
        name: test
        entry: ./scripts/pytest.sh
        language: system
        types: [python]
        pass_filenames: false
      - id: commit-msg
        name: conventional-commit-messages
        language: pygrep
        entry: "^(chore|test|feat|fix|build|docs|refactor)!?:.*$"
        args: [--multiline, --negate] # fails if the entry is NOT matched
        stages: [commit-msg]